#
# Macro file for MyExample
#
# set verbose level for this run
#

/run/verbose    1
/event/verbose  1
/process/verbose 10

# Set the particle source properties
# 
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 -.5 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    100 MeV
# Set the initial kinematic and run 3 events
#

#/run/beamOn 100000
#/run/beamOn 5000
/run/beamOn 1
