#
# Macro file for MyExample
#
# set verbose level for this run
#

/run/verbose    1
/run/setCut     0.04 mm
/event/verbose  1
/process/verbose 10
/random/setSeeds 770353837 70597151
#/random/setSeeds 575841909 838392975
# Set the particle source properties
# 

########################
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    42.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    45.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    46.50 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    48.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    49.50 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    50.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    54.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    65.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    70.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    80.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    85.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    100.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    105.629 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    118.103 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    125.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    130.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    135.646 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    160.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    165.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    186.871 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    205.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    220.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    245.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    250.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    300.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    315.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    400.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    500.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    584.018 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    711.946 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    870.123 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    1227.573 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    1446.583 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi+
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    1865.294 MeV
########################



/run/beamOn 200000
#/run/beamOn 1
