#
# Macro file for MyExample
#
# set verbose level for this run
#

/run/verbose    1
/run/setCut     0.04 mm
/event/verbose  1
/process/verbose 10
/random/setSeeds 770353863 70597177
#/random/setSeeds 575841909 838392975
# Set the particle source properties
# 


########################
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    37.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    50.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    52.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    68.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    70.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    83.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    100.00 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    125.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    151.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    165.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    187.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    233.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    280.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    410.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    464.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    492.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    410.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    464.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    492.000 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    711.946 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    870.123 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    1227.573 MeV
########################

########################
/gps/source/add  1
/gps/particle    pi-
/gps/direction   0 0 1
/gps/pos/type    Plane 
/gps/pos/shape   Circle
/gps/pos/centre  0 0 0 mm
/gps/pos/radius  5 cm

/gps/ene/type    Mono
/gps/ene/mono    1446.583 MeV
########################



/run/beamOn 200000
#/run/beamOn 1
